/*
 * Author: Aonghus Lawlor aonghus.lawlor@ucd.ie
 * 2019
 *
 * Do not edit this file! It will be updated during the module.
 *
 */

package project20280.interfaces;

import java.util.Collection;
import java.util.Iterator;
import java.util.ListIterator;

public interface List<E> extends Iterable<E> {

    int size();

    boolean isEmpty();

    boolean contains(Object o);

    E get(int i);

    E set(int index, E value);

    void add(int i, E e);

    void addFirst(E e);

    void addLast(E e);

    E remove(int i);

    int indexOf(Object o);

    int lastIndexOf(Object o);

    ListIterator<E> listIterator();

    ListIterator<E> listIterator(int index);

    java.util.List<E> subList(int fromIndex, int toIndex);

    E removeFirst();

    E removeLast();

    Iterator<E> iterator();

    Object[] toArray();

    <T> T[] toArray(T[] a);

    boolean add(E e);

    boolean remove(Object o);

    boolean containsAll(Collection<?> c);

    boolean addAll(Collection<? extends E> c);

    boolean addAll(int index, Collection<? extends E> c);

    boolean removeAll(Collection<?> c);

    boolean retainAll(Collection<?> c);

    void clear();
}
